ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';

CREATE TABLE VENTAS.clienteoracle (
	identificacion VARCHAR2(10) PRIMARY KEY NOT NULL,
	nombre VARCHAR2(50) NOT NULL,
	edad INTEGER NOT NULL,
	correo VARCHAR2(50) NOT NULL
);
DROP TABLE VENTAS.CLIENTEORACLE ;
CREATE TABLE VENTAS.productoracle (
	codigo_producto VARCHAR2(10) PRIMARY KEY NOT NULL,
	nombre VARCHAR2(50) NOT NULL,
	stock INTEGER NOT NULL,
	valor_unitario NUMERIC NOT NULL	
);
DROP TABLE VENTAS.PRODUCTORACLE ;
CREATE TABLE VENTAS.facturaoracle (
	id_factura VARCHAR2(10) PRIMARY KEY NOT NULL,
	fecha DATE NOT NULL,
	cant_total INTEGER NOT NULL,
	valor_total NUMERIC NOT NULL,
	estado_pedido VARCHAR2(20) NOT NULL,
	cliente_id_fk VARCHAR2(10) NOT NULL,
	producto_codigo_fk VARCHAR2(10) NOT NULL,
	constraint fk_cliente_id FOREIGN KEY (cliente_id_fk) REFERENCES VENTAS.clienteoracle(identificacion),
	constraint producto_id FOREIGN KEY (producto_codigo_fk) REFERENCES VENTAS.productoracle(codigo_producto)
);
DROP TABLE VENTAS.FACTURAORACLE ;
ALTER USER VENTAS QUOTA UNLIMITED ON USERS;

INSERT INTO VENTAS.clienteoracle(identificacion,nombre,edad,correo) VALUES
('1098675834','Fernanda', 19, 'fernanda@gmail.com');
INSERT INTO VENTAS.clienteoracle(identificacion,nombre,edad,correo) VALUES
('1993546789','Maicol', 21, 'maicol@gmail.com');
INSERT INTO VENTAS.clienteoracle(identificacion,nombre,edad,correo) VALUES
('1002543765','Alex', 25, 'alex@gmail.com');

SELECT * FROM VENTAS.clienteoracle;

INSERT INTO VENTAS.productoracle(codigo_producto,nombre,stock,valor_unitario)VALUES
('2352','Mesa', 32,127990);
INSERT INTO VENTAS.productoracle(codigo_producto,nombre,stock,valor_unitario)VALUES
('4356','Silla', 35,97960);
INSERT INTO VENTAS.productoracle(codigo_producto,nombre,stock,valor_unitario)VALUES
('6789','Escritorio', 25,235900);

SELECT * FROM VENTAS.productoracle;


INSERT INTO VENTAS.facturaoracle(id_factura,fecha,cant_total,valor_total,estado_pedido,cliente_id_fk,producto_codigo_fk) VALUES
('F002', TRUNC(TO_DATE('2024-08-30', 'YYYY-MM-DD')),10,267800,'ENTREGADO','1002543765','4356');
INSERT INTO VENTAS.facturaoracle(id_factura,fecha,cant_total,valor_total,estado_pedido,cliente_id_fk,producto_codigo_fk) VALUES
('F003','2024-08-29',27,986500,'BLOQUEADO','1098675834','6789');
INSERT INTO VENTAS.facturaoracle(id_factura,fecha,cant_total,valor_total,estado_pedido,cliente_id_fk,producto_codigo_fk) VALUES
('F004','2024-08-29',1,87320,'BLOQUEADO','1993546789','6789');



DELETE FROM VENTAS.FACTURAORACLE f ;
SELECT * FROM VENTAS.facturaoracle;

CREATE TABLE VENTAS.auditoria (
    id_auditoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_inicio DATE NOT NULL,
    fecha_final DATE NOT NULL,
    factura_id VARCHAR2(10) NOT NULL,
    pedido_estado VARCHAR2(20)
);
SELECT * FROM VENTAS.AUDITORIA a ;

DROP TABLE VENTAS.AUDITORIA ;
CREATE OR REPLACE PROCEDURE VENTAS.generar_auditoria_oracle(v_fecha_inicio IN DATE, v_fecha_final IN DATE)
IS
    v_id_factura VARCHAR2(10);
    v_estado_pedido VARCHAR2(255);
    fecha_factura DATE;
BEGIN
    FOR venta IN (SELECT fecha, id_factura, estado_pedido FROM VENTAS.facturaoracle) LOOP
        -- Asignar valores desde la consulta
        v_id_factura := venta.id_factura;
        v_estado_pedido := venta.estado_pedido;
        fecha_factura := venta.fecha;

        -- Comparar fechas directamente
        IF fecha_factura >= v_fecha_inicio AND fecha_factura <= v_fecha_final THEN
            INSERT INTO VENTAS.auditoria(fecha_inicio, fecha_final, factura_id, pedido_estado)
            VALUES (v_fecha_inicio, v_fecha_final, v_id_factura, v_estado_pedido);
        END IF;
    END LOOP;
END;

CALL VENTAS.generar_auditoria_oracle(TO_DATE('2024-08-29', 'YYYY-MM-DD'), TO_DATE('2024-08-30', 'YYYY-MM-DD'));

CREATE OR REPLACE PROCEDURE VENTAS.simular_ventas_mes_oracle(v_codigo_producto varchar)
IS
	v_dia INTEGER := 1;
	v_identificacion VARCHAR2(255);
	cantidad_random INTEGER;
	valor_total_ INTEGER;
	v_valor_producto INTEGER;
BEGIN
	SELECT valor_unitario INTO v_valor_producto
	FROM VENTAS.productoracle 
	WHERE codigo_producto = v_codigo_producto;

	WHILE v_dia <=30 LOOP
		FOR cliente IN (SELECT identificacion FROM VENTAS.clienteoracle)
		LOOP
			cantidad_random := FLOOR(1+(10-1+1) * 3);
			valor_total_ := cantidad_random*v_valor_producto;
			v_identificacion:= cliente.identificacion;
			INSERT INTO VENTAS.facturaoracle(id_factura,fecha,cant_total,valor_total,estado_pedido,cliente_id_fk,producto_codigo_fk)
			VALUES (
				'FF-' || DBMS_RANDOM.STRING('x', 6),
				CURRENT_DATE,
				cantidad_random,
				valor_total_,
				'PENDIENTE',
				v_identificacion,
				v_codigo_producto);
		END LOOP;
		v_dia := v_dia+1;
	END LOOP;
END;

SELECT * FROM VENTAS.PRODUCTORACLE p WHERE CODIGO_PRODUCTO = '2352';
SELECT * FROM VENTAS.FACTURAORACLE f ;
CALL VENTAS.simular_ventas_mes_oracle('2352');